import type { StudioLocale } from "../types";

const productionCopy = {
  "zh-CN": {
    artDepartment: "美术部门",
    scriptDepartment: "剧本交付",
    previsDepartment: "导演与预演",
    shotDesign: "镜头设计",
    shotList: "镜头表",
    animatic: "动态分镜",
    vfxWorkspace: "VFX 制作",
    vfxBreakdown: "VFX Breakdown",
    vfxShotPackage: "VFX 镜头包",
    addVfxShot: "标记为 VFX 镜头",
    newVfxVersion: "新建版本",
    createVersion: "创建新版本",
    vfxVersionCreated: "VFX 镜头新版本已创建",
    vfxShotAdded: "VFX 镜头已加入制作",
    vfxRequiredFields: "请完整填写 VFX 摘要和色彩空间",
    vfxCategory: "VFX 类型",
    vfxComplexity: "复杂度",
    colorSpace: "工作色彩空间",
    vfxSummary: "镜头处理说明",
    plateRequirements: "Plate 要求",
    elementRequirements: "Element 要求",
    trackingRequirements: "跟踪要求",
    matteRequirements: "遮罩与 Roto 要求",
    compositeNotes: "合成说明",
    vfxSources: "Plate 与 Element 来源",
    plate: "Plate",
    element: "Element",
    composite: "Comp",
    shotQc: "镜头 QC",
    notes: "备注",
    vfxShots: "VFX 镜头",
    nonVfxShots: "普通镜头",
    noVfxShots: "当前剧集还没有 VFX 镜头",
    notVfxShot: "当前镜头未标记为 VFX，不会创建任何 VFX 生成请求",
    dependencyGraph: "镜头依赖",
    versionHistory: "版本历史",
    restoreVersion: "恢复此版本",
    confirmRestore: "恢复后会以历史内容创建一个新的草稿版本，当前版本将保留在审计记录中。",
    restored: "历史版本已恢复为新草稿",
    pipeline: "制作链路",
    queueElement: "生成 Element",
    queueComposite: "生成 Comp",
    visualBible: "视觉圣经",
    colorScript: "色彩脚本",
    specifications: "资产规格",
    deliverables: "制作交付物",
    newDeliverable: "新建交付物",
    noDeliverables: "当前范围还没有交付物",
    departmentLead: "主责 Agent",
    qualityGates: "质量门",
    version: "版本",
    sources: "来源",
    dependencies: "依赖",
    noDependencies: "无上游依赖",
    blockers: "阻塞",
    ready: "依赖已满足",
    cost: "成本",
    creativeDirection: "创作方向",
    directives: "执行规则",
    constraints: "限制条件",
    approval: "审批",
    submit: "提交评审",
    approve: "批准",
    reject: "驳回",
    lock: "锁定",
    supersede: "废弃版本",
    created: "交付物已创建",
    updated: "交付物状态已更新",
    actionFailed: "交付物操作失败",
    type: "交付物类型",
    title: "标题",
    titlePlaceholder: "输入可识别的版本标题",
    summary: "核心说明",
    summaryPlaceholder: "定义视觉或剧本方向、目标与关键决策",
    directivesPlaceholder: "每行一条执行规则",
    constraintsPlaceholder: "每行一条不可违背的限制",
    sourceAssets: "参考资产",
    upstream: "上游交付物",
    create: "创建草稿",
    cancel: "取消",
    confirmLock: "确认锁定这个版本？锁定后应由新版本承接修改。",
    confirmSupersede: "确认废弃这个版本？依赖它的下游会被标记为失效。",
    confirm: "确认",
    rejectionNote: "驳回原因",
    rejectionPlaceholder: "说明需要修改的内容",
    pendingGate: "待审批",
    sourceCount: "项来源",
    blockedDependency: "上游未批准或版本已失效",
    loading: "正在载入制作交付物",
    retry: "重试",
  },
  en: {
    artDepartment: "Art department",
    scriptDepartment: "Script deliverables",
    previsDepartment: "Direction & previs",
    shotDesign: "Shot design",
    shotList: "Shot list",
    animatic: "Animatic",
    vfxWorkspace: "VFX production",
    vfxBreakdown: "VFX breakdown",
    vfxShotPackage: "VFX shot package",
    addVfxShot: "Mark as VFX shot",
    newVfxVersion: "New version",
    createVersion: "Create new version",
    vfxVersionCreated: "New VFX shot version created",
    vfxShotAdded: "VFX shot added to production",
    vfxRequiredFields: "Complete the VFX summary and working color space",
    vfxCategory: "VFX category",
    vfxComplexity: "Complexity",
    colorSpace: "Working color space",
    vfxSummary: "Shot treatment",
    plateRequirements: "Plate requirements",
    elementRequirements: "Element requirements",
    trackingRequirements: "Tracking requirements",
    matteRequirements: "Matte and roto requirements",
    compositeNotes: "Composite notes",
    vfxSources: "Plate and element sources",
    plate: "Plate",
    element: "Element",
    composite: "Comp",
    shotQc: "Shot QC",
    notes: "Notes",
    vfxShots: "VFX shots",
    nonVfxShots: "Non-VFX shots",
    noVfxShots: "No VFX shots in this episode yet",
    notVfxShot: "This shot is not marked for VFX, so no VFX generation requests will be created",
    dependencyGraph: "Shot dependencies",
    versionHistory: "Version history",
    restoreVersion: "Restore this version",
    confirmRestore: "Restoring creates a new draft from this history entry and preserves the current version in the audit trail.",
    restored: "Historical version restored as a new draft",
    pipeline: "Production pipeline",
    queueElement: "Generate element",
    queueComposite: "Generate comp",
    visualBible: "Visual bible",
    colorScript: "Color script",
    specifications: "Asset specifications",
    deliverables: "Production deliverables",
    newDeliverable: "New deliverable",
    noDeliverables: "No deliverables in this scope yet",
    departmentLead: "Responsible agents",
    qualityGates: "Quality gates",
    version: "Version",
    sources: "Sources",
    dependencies: "Dependencies",
    noDependencies: "No upstream dependencies",
    blockers: "Blocked",
    ready: "Dependencies ready",
    cost: "Cost",
    creativeDirection: "Creative direction",
    directives: "Execution rules",
    constraints: "Constraints",
    approval: "Approval",
    submit: "Submit for review",
    approve: "Approve",
    reject: "Reject",
    lock: "Lock",
    supersede: "Supersede version",
    created: "Deliverable created",
    updated: "Deliverable status updated",
    actionFailed: "Deliverable action failed",
    type: "Deliverable type",
    title: "Title",
    titlePlaceholder: "Enter a recognizable version title",
    summary: "Core brief",
    summaryPlaceholder: "Define direction, goals, and key decisions",
    directivesPlaceholder: "One execution rule per line",
    constraintsPlaceholder: "One non-negotiable constraint per line",
    sourceAssets: "Reference assets",
    upstream: "Upstream deliverables",
    create: "Create draft",
    cancel: "Cancel",
    confirmLock: "Lock this version? Further changes should use a new version.",
    confirmSupersede:
      "Supersede this version? Dependent work will be marked stale.",
    confirm: "Confirm",
    rejectionNote: "Rejection reason",
    rejectionPlaceholder: "Describe the changes required",
    pendingGate: "Pending",
    sourceCount: "sources",
    blockedDependency: "Upstream is unapproved or stale",
    loading: "Loading production deliverables",
    retry: "Retry",
  },
} as const;

const labels = {
  agents: {
    producer: ["制片人", "Producer"],
    director: ["导演", "Director"],
    story_editor: ["故事编辑", "Story editor"],
    screenwriter: ["编剧", "Screenwriter"],
    script_coordinator: ["剧本统筹", "Script coordinator"],
    script_supervisor: ["场记", "Script supervisor"],
    casting_director: ["选角指导", "Casting director"],
    production_designer: ["制作设计", "Production designer"],
    art_director: ["美术指导", "Art director"],
    character_designer: ["角色设计", "Character designer"],
    environment_designer: ["场景设计", "Environment designer"],
    prop_costume_designer: ["道具服装设计", "Prop & costume designer"],
    color_script_artist: ["色彩脚本", "Color script artist"],
    cinematographer: ["摄影指导", "Cinematographer"],
    storyboard_director: ["分镜导演", "Storyboard director"],
    acting_director: ["表演指导", "Acting director"],
    shot_producer: ["镜头制片", "Shot producer"],
    generation_operator: ["生成操作", "Generation operator"],
    continuity_supervisor: ["连续性监督", "Continuity supervisor"],
    vfx_supervisor: ["视效总监", "VFX supervisor"],
    fx_artist: ["特效师", "FX artist"],
    compositor: ["合成师", "Compositor"],
    editor: ["剪辑师", "Editor"],
    sound_supervisor: ["声音总监", "Sound supervisor"],
    dialogue_editor: ["对白编辑", "Dialogue editor"],
    foley_artist: ["拟音师", "Foley artist"],
    music_supervisor: ["音乐总监", "Music supervisor"],
    re_recording_mixer: ["混录师", "Re-recording mixer"],
    colorist: ["调色师", "Colorist"],
    online_editor: ["Online 剪辑师", "Online editor"],
    qc_supervisor: ["质量监督", "QC supervisor"],
    delivery_producer: ["交付制片", "Delivery producer"],
  },
  departments: {
    development: ["项目开发", "Development"],
    script: ["剧本部门", "Script"],
    art: ["美术部门", "Art"],
    previs: ["导演与预演", "Direction & previs"],
    shot: ["镜头生产", "Shot production"],
    vfx: ["VFX 制作", "VFX production"],
    sound: ["声音与剪辑", "Sound & editorial"],
    post: ["调色与 Online", "Color & online"],
    delivery: ["母版交付", "Mastering & delivery"],
  },
  gates: {
    creative: ["创意", "Creative"],
    production: ["制片", "Production"],
    continuity: ["连续性", "Continuity"],
    art: ["美术", "Art"],
    camera: ["摄影", "Camera"],
    vfx: ["视效", "VFX"],
    technical: ["技术", "Technical"],
    sound: ["声音", "Sound"],
    legal: ["版权", "Legal"],
    content: ["内容", "Content"],
    delivery: ["交付", "Delivery"],
  },
  statuses: {
    draft: ["草稿", "Draft"],
    review: ["评审中", "In review"],
    approved: ["已批准", "Approved"],
    locked: ["已锁定", "Locked"],
    stale: ["已失效", "Stale"],
    superseded: ["已废弃", "Superseded"],
    pending: ["待审批", "Pending"],
    rejected: ["已驳回", "Rejected"],
  },
  types: {
    creative_brief: ["创作简报", "Creative brief"],
    production_bible: ["制作圣经", "Production bible"],
    story_bible: ["故事圣经", "Story bible"],
    screenplay_lock: ["剧本锁定稿", "Screenplay lock"],
    script_breakdown: ["剧本拆解", "Script breakdown"],
    scene_schedule: ["场次计划", "Scene schedule"],
    continuity_bible: ["连续性圣经", "Continuity bible"],
    visual_bible: ["视觉圣经", "Visual bible"],
    color_script: ["色彩脚本", "Color script"],
    character_design: ["角色设计规格", "Character design"],
    environment_design: ["场景设计规格", "Environment design"],
    prop_costume_design: ["道具服装规格", "Prop & costume design"],
    directors_treatment: ["导演阐述", "Director's treatment"],
    blocking: ["场面调度", "Blocking"],
    shot_list: ["镜头表", "Shot list"],
    cinematography_plan: ["摄影方案", "Cinematography plan"],
    performance_plan: ["表演方案", "Performance plan"],
    previs: ["预演方案", "Previs"],
    animatic: ["动态分镜", "Animatic"],
    shot_package: ["镜头任务包", "Shot package"],
    selects: ["选片记录", "Selects"],
    shot_qc: ["镜头质量报告", "Shot QC"],
    vfx_breakdown: ["VFX 拆解", "VFX breakdown"],
    vfx_shot_package: ["VFX 镜头包", "VFX shot package"],
    composite_qc: ["合成质量报告", "Composite QC"],
    dialogue_adr: ["对白与 ADR", "Dialogue & ADR"],
    sfx_foley: ["音效与拟音", "SFX & Foley"],
    music_cue_sheet: ["音乐 Cue Sheet", "Music cue sheet"],
    cue_sheet: ["声音 Cue Sheet", "Sound cue sheet"],
    sound_mix: ["混录母版", "Sound mix"],
    sound_post_package: ["声音后期包", "Sound post package"],
    edit_decision_list: ["剪辑决策表", "Edit decision list"],
    picture_lock: ["画面锁定版", "Picture lock"],
    color_master: ["调色母版", "Color master"],
    online_master: ["Online 母版", "Online master"],
    post_master_package: ["后期母版包", "Post master package"],
    qc_report: ["母版质检报告", "Master QC report"],
    subtitle_package: ["字幕包", "Subtitle package"],
    delivery_master: ["交付母版", "Delivery master"],
  },
  vfxCategories: {
    cleanup: ["清理与移除", "Cleanup"],
    screen_replacement: ["屏幕替换", "Screen replacement"],
    set_extension: ["场景延伸", "Set extension"],
    matte_painting: ["数字绘景", "Matte painting"],
    simulation: ["物理特效", "Simulation"],
    creature: ["生物与角色特效", "Creature"],
    environment: ["环境特效", "Environment"],
  },
  vfxComplexities: {
    low: ["低", "Low"],
    medium: ["中", "Medium"],
    high: ["高", "High"],
  },
  vfxQc: {
    edges: ["边缘与遮罩", "Edges and mattes"],
    motion: ["运动与跟踪", "Motion and tracking"],
    lighting: ["光照匹配", "Lighting match"],
    color: ["色彩匹配", "Color match"],
    grain: ["颗粒与锐度", "Grain and sharpness"],
    integration: ["整体融合", "Integration"],
  },
  vfxQcStatuses: {
    pending: ["待检查", "Pending"],
    pass: ["通过", "Pass"],
    fail: ["未通过", "Fail"],
  },
  vfxTaskStatuses: {
    waiting: ["待素材", "Waiting for media"],
    blocked: ["被阻塞", "Blocked"],
    ready: ["可执行", "Ready"],
    queued: ["排队中", "Queued"],
    running: ["处理中", "Running"],
    succeeded: ["已完成", "Completed"],
    failed: ["失败", "Failed"],
    canceled: ["已取消", "Canceled"],
  },
} as const;

export function getProductionCopy(locale: StudioLocale) {
  return productionCopy[locale];
}

export function productionLabel(
  locale: StudioLocale,
  group: keyof typeof labels,
  value: string,
) {
  const entry = (labels[group] as Record<string, readonly [string, string]>)[
    value
  ];
  return entry?.[locale === "zh-CN" ? 0 : 1] ?? value.replaceAll("_", " ");
}
