import type { StudioLocale } from "../types";

const productionCopy = {
  "zh-CN": {
    artDepartment: "美术部门",
    scriptDepartment: "剧本交付",
    previsDepartment: "导演与预演",
    shotDesign: "镜头设计",
    shotList: "镜头表",
    animatic: "动态分镜",
    visualBible: "视觉圣经",
    colorScript: "色彩脚本",
    specifications: "资产规格",
    deliverables: "制作交付物",
    newDeliverable: "新建交付物",
    noDeliverables: "当前范围还没有交付物",
    departmentLead: "主责 Agent",
    qualityGates: "质量门",
    version: "版本",
    sources: "来源",
    dependencies: "依赖",
    noDependencies: "无上游依赖",
    blockers: "阻塞",
    ready: "依赖已满足",
    cost: "成本",
    creativeDirection: "创作方向",
    directives: "执行规则",
    constraints: "限制条件",
    approval: "审批",
    submit: "提交评审",
    approve: "批准",
    reject: "驳回",
    lock: "锁定",
    supersede: "废弃版本",
    created: "交付物已创建",
    updated: "交付物状态已更新",
    actionFailed: "交付物操作失败",
    type: "交付物类型",
    title: "标题",
    titlePlaceholder: "输入可识别的版本标题",
    summary: "核心说明",
    summaryPlaceholder: "定义视觉或剧本方向、目标与关键决策",
    directivesPlaceholder: "每行一条执行规则",
    constraintsPlaceholder: "每行一条不可违背的限制",
    sourceAssets: "参考资产",
    upstream: "上游交付物",
    create: "创建草稿",
    cancel: "取消",
    confirmLock: "确认锁定这个版本？锁定后应由新版本承接修改。",
    confirmSupersede: "确认废弃这个版本？依赖它的下游会被标记为失效。",
    confirm: "确认",
    rejectionNote: "驳回原因",
    rejectionPlaceholder: "说明需要修改的内容",
    pendingGate: "待审批",
    sourceCount: "项来源",
    blockedDependency: "上游未批准或版本已失效",
    loading: "正在载入制作交付物",
    retry: "重试",
  },
  en: {
    artDepartment: "Art department",
    scriptDepartment: "Script deliverables",
    previsDepartment: "Direction & previs",
    shotDesign: "Shot design",
    shotList: "Shot list",
    animatic: "Animatic",
    visualBible: "Visual bible",
    colorScript: "Color script",
    specifications: "Asset specifications",
    deliverables: "Production deliverables",
    newDeliverable: "New deliverable",
    noDeliverables: "No deliverables in this scope yet",
    departmentLead: "Responsible agents",
    qualityGates: "Quality gates",
    version: "Version",
    sources: "Sources",
    dependencies: "Dependencies",
    noDependencies: "No upstream dependencies",
    blockers: "Blocked",
    ready: "Dependencies ready",
    cost: "Cost",
    creativeDirection: "Creative direction",
    directives: "Execution rules",
    constraints: "Constraints",
    approval: "Approval",
    submit: "Submit for review",
    approve: "Approve",
    reject: "Reject",
    lock: "Lock",
    supersede: "Supersede version",
    created: "Deliverable created",
    updated: "Deliverable status updated",
    actionFailed: "Deliverable action failed",
    type: "Deliverable type",
    title: "Title",
    titlePlaceholder: "Enter a recognizable version title",
    summary: "Core brief",
    summaryPlaceholder: "Define direction, goals, and key decisions",
    directivesPlaceholder: "One execution rule per line",
    constraintsPlaceholder: "One non-negotiable constraint per line",
    sourceAssets: "Reference assets",
    upstream: "Upstream deliverables",
    create: "Create draft",
    cancel: "Cancel",
    confirmLock: "Lock this version? Further changes should use a new version.",
    confirmSupersede:
      "Supersede this version? Dependent work will be marked stale.",
    confirm: "Confirm",
    rejectionNote: "Rejection reason",
    rejectionPlaceholder: "Describe the changes required",
    pendingGate: "Pending",
    sourceCount: "sources",
    blockedDependency: "Upstream is unapproved or stale",
    loading: "Loading production deliverables",
    retry: "Retry",
  },
} as const;

const labels = {
  agents: {
    producer: ["制片人", "Producer"],
    director: ["导演", "Director"],
    story_editor: ["故事编辑", "Story editor"],
    screenwriter: ["编剧", "Screenwriter"],
    script_coordinator: ["剧本统筹", "Script coordinator"],
    script_supervisor: ["场记", "Script supervisor"],
    casting_director: ["选角指导", "Casting director"],
    production_designer: ["制作设计", "Production designer"],
    art_director: ["美术指导", "Art director"],
    character_designer: ["角色设计", "Character designer"],
    environment_designer: ["场景设计", "Environment designer"],
    prop_costume_designer: ["道具服装设计", "Prop & costume designer"],
    color_script_artist: ["色彩脚本", "Color script artist"],
    cinematographer: ["摄影指导", "Cinematographer"],
    storyboard_director: ["分镜导演", "Storyboard director"],
    acting_director: ["表演指导", "Acting director"],
  },
  departments: {
    development: ["项目开发", "Development"],
    script: ["剧本部门", "Script"],
    art: ["美术部门", "Art"],
    previs: ["导演与预演", "Direction & previs"],
  },
  gates: {
    creative: ["创意", "Creative"],
    production: ["制片", "Production"],
    continuity: ["连续性", "Continuity"],
    art: ["美术", "Art"],
    camera: ["摄影", "Camera"],
  },
  statuses: {
    draft: ["草稿", "Draft"],
    review: ["评审中", "In review"],
    approved: ["已批准", "Approved"],
    locked: ["已锁定", "Locked"],
    stale: ["已失效", "Stale"],
    superseded: ["已废弃", "Superseded"],
    pending: ["待审批", "Pending"],
    rejected: ["已驳回", "Rejected"],
  },
  types: {
    creative_brief: ["创作简报", "Creative brief"],
    production_bible: ["制作圣经", "Production bible"],
    story_bible: ["故事圣经", "Story bible"],
    screenplay_lock: ["剧本锁定稿", "Screenplay lock"],
    script_breakdown: ["剧本拆解", "Script breakdown"],
    scene_schedule: ["场次计划", "Scene schedule"],
    continuity_bible: ["连续性圣经", "Continuity bible"],
    visual_bible: ["视觉圣经", "Visual bible"],
    color_script: ["色彩脚本", "Color script"],
    character_design: ["角色设计规格", "Character design"],
    environment_design: ["场景设计规格", "Environment design"],
    prop_costume_design: ["道具服装规格", "Prop & costume design"],
    directors_treatment: ["导演阐述", "Director's treatment"],
    blocking: ["场面调度", "Blocking"],
    shot_list: ["镜头表", "Shot list"],
    cinematography_plan: ["摄影方案", "Cinematography plan"],
    performance_plan: ["表演方案", "Performance plan"],
    previs: ["预演方案", "Previs"],
    animatic: ["动态分镜", "Animatic"],
  },
} as const;

export function getProductionCopy(locale: StudioLocale) {
  return productionCopy[locale];
}

export function productionLabel(
  locale: StudioLocale,
  group: keyof typeof labels,
  value: string,
) {
  const entry = (labels[group] as Record<string, readonly [string, string]>)[
    value
  ];
  return entry?.[locale === "zh-CN" ? 0 : 1] ?? value.replaceAll("_", " ");
}
