-- Baseline schema for MySQL deployments. Existing development databases created
-- with `prisma db push` should be baselined before running `prisma migrate deploy`.
CREATE TABLE `users` (`id` VARCHAR(191) NOT NULL, `email` VARCHAR(191) NULL, `password_hash` VARCHAR(191) NULL, `display_name` VARCHAR(191) NOT NULL, `anonymous` BOOLEAN NOT NULL DEFAULT false, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, UNIQUE INDEX `users_email_key`(`email`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `sessions` (`id` VARCHAR(191) NOT NULL, `user_id` VARCHAR(191) NOT NULL, `expires_at` DATETIME(3) NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `sessions_user_id_idx`(`user_id`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `channels` (`id` VARCHAR(191) NOT NULL, `user_id` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `protocol` VARCHAR(191) NOT NULL, `base_url` VARCHAR(191) NOT NULL, `encrypted_api_keys` TEXT NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, INDEX `channels_user_id_created_at_idx`(`user_id`, `created_at`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `models` (`id` VARCHAR(191) NOT NULL, `channel_id` VARCHAR(191) NOT NULL, `model_id` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `model_type` VARCHAR(191) NOT NULL, `capabilities_json` TEXT NOT NULL, `selected` BOOLEAN NOT NULL DEFAULT true, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, INDEX `models_channel_id_idx`(`channel_id`), UNIQUE INDEX `models_channel_id_model_id_key`(`channel_id`, `model_id`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `projects` (`id` VARCHAR(191) NOT NULL, `user_id` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `description` TEXT NULL, `last_accessed_at` DATETIME(3) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, INDEX `projects_user_id_updated_at_idx`(`user_id`, `updated_at`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `project_configs` (`id` VARCHAR(191) NOT NULL, `project_id` VARCHAR(191) NOT NULL, `analysis_model` VARCHAR(191) NULL, `character_model` VARCHAR(191) NULL, `location_model` VARCHAR(191) NULL, `storyboard_model` VARCHAR(191) NULL, `edit_model` VARCHAR(191) NULL, `video_model` VARCHAR(191) NULL, `audio_model` VARCHAR(191) NULL, `video_ratio` VARCHAR(191) NOT NULL DEFAULT '9:16', `video_resolution` VARCHAR(191) NOT NULL DEFAULT '720p', `art_style` VARCHAR(191) NOT NULL DEFAULT 'american-comic', `tts_rate` VARCHAR(191) NOT NULL DEFAULT '+50%', `workflow_mode` VARCHAR(191) NOT NULL DEFAULT 'novel-promotion', `global_asset_text` TEXT NULL, `capability_overrides_json` TEXT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, UNIQUE INDEX `project_configs_project_id_key`(`project_id`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `episodes` (`id` VARCHAR(191) NOT NULL, `project_id` VARCHAR(191) NOT NULL, `episode_number` INTEGER NOT NULL, `name` VARCHAR(191) NOT NULL, `description` TEXT NULL, `novel_text` LONGTEXT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, INDEX `episodes_project_id_episode_number_idx`(`project_id`, `episode_number`), UNIQUE INDEX `episodes_project_id_episode_number_key`(`project_id`, `episode_number`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `media_tasks` (`id` VARCHAR(191) NOT NULL, `user_id` VARCHAR(191) NOT NULL, `idempotency_key` VARCHAR(191) NULL, `project_id` VARCHAR(191) NULL, `episode_id` VARCHAR(191) NULL, `target_type` VARCHAR(191) NULL, `target_id` VARCHAR(191) NULL, `status` VARCHAR(191) NOT NULL, `kind` VARCHAR(191) NOT NULL, `provider` VARCHAR(191) NOT NULL, `protocol` VARCHAR(191) NOT NULL, `model` VARCHAR(191) NOT NULL, `provider_task_id` VARCHAR(191) NULL, `payload` JSON NOT NULL, `error` JSON NULL, `retry_count` INTEGER NOT NULL DEFAULT 0, `max_retries` INTEGER NOT NULL DEFAULT 2, `progress` INTEGER NOT NULL DEFAULT 0, `progress_message` TEXT NULL, `queue_job_id` VARCHAR(191) NULL, `cancel_requested_at` DATETIME(3) NULL, `heartbeat_at` DATETIME(3) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, `started_at` DATETIME(3) NULL, `completed_at` DATETIME(3) NULL, INDEX `media_tasks_user_id_updated_at_idx`(`user_id`, `updated_at`), INDEX `media_tasks_project_id_updated_at_idx`(`project_id`, `updated_at`), INDEX `media_tasks_episode_id_updated_at_idx`(`episode_id`, `updated_at`), UNIQUE INDEX `media_tasks_user_id_idempotency_key_key`(`user_id`, `idempotency_key`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `media_task_events` (`id` VARCHAR(191) NOT NULL, `task_id` VARCHAR(191) NOT NULL, `type` VARCHAR(191) NOT NULL, `status` VARCHAR(191) NULL, `progress` INTEGER NULL, `message` TEXT NULL, `payload` JSON NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `media_task_events_task_id_created_at_idx`(`task_id`, `created_at`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `media_assets` (`id` VARCHAR(191) NOT NULL, `task_id` VARCHAR(191) NOT NULL, `kind` VARCHAR(191) NOT NULL, `storage_key` VARCHAR(191) NULL, `url` TEXT NULL, `mime_type` VARCHAR(191) NULL, `metadata_json` TEXT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `media_assets_task_id_idx`(`task_id`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `media_tasks` ADD COLUMN `channel_id` VARCHAR(191) NULL;
CREATE INDEX `media_tasks_channel_id_updated_at_idx` ON `media_tasks`(`channel_id`, `updated_at`);
ALTER TABLE `sessions` ADD CONSTRAINT `sessions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `channels` ADD CONSTRAINT `channels_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `models` ADD CONSTRAINT `models_channel_id_fkey` FOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `projects` ADD CONSTRAINT `projects_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `project_configs` ADD CONSTRAINT `project_configs_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `episodes` ADD CONSTRAINT `episodes_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `media_tasks` ADD CONSTRAINT `media_tasks_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `media_tasks` ADD CONSTRAINT `media_tasks_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `media_tasks` ADD CONSTRAINT `media_tasks_episode_id_fkey` FOREIGN KEY (`episode_id`) REFERENCES `episodes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `media_task_events` ADD CONSTRAINT `media_task_events_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `media_tasks`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `media_assets` ADD CONSTRAINT `media_assets_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `media_tasks`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
